2018/01/17 07:04:49 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'blog' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/blog/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/blog/index.php?r=gii/default/index
---
2018/01/17 10:35:16 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php?r=index
---
2018/01/17 11:19:00 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''aaaa' LIMIT 1' at line 1. The SQL statement executed was: SELECT * FROM `tbl_user` `t` WHERE LOWER(username)? LIMIT 1.
2018/01/17 11:19:00 [error] [exception.CDbException] CDbException: CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''aaaa' LIMIT 1' at line 1. The SQL statement executed was: SELECT * FROM `tbl_user` `t` WHERE LOWER(username)? LIMIT 1 in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1359): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1464): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\htdocs\blog\protected\components\UserIdentity.php(39): CActiveRecord->find('LOWER(username)...', Array)
#4 C:\xampp\htdocs\blog\protected\models\LoginForm.php(53): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#8 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(90): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/blog/index.php?r=site/login
HTTP_REFERER=http://localhost/blog/index.php?r=site/login
---
2018/01/17 11:23:10 [error] [exception.CException] CException: Property "User.usernmae" is not defined. in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('usernmae')
#1 C:\xampp\htdocs\blog\protected\components\UserIdentity.php(48): CActiveRecord->__get('usernmae')
#2 C:\xampp\htdocs\blog\protected\models\LoginForm.php(53): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#6 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(90): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/blog/index.php?r=site/login
HTTP_REFERER=http://localhost/blog/index.php?r=site/login
---
2018/01/18 03:29:15 [error] [php] Object of class User could not be converted to string (C:\xampp\htdocs\blog\protected\components\UserIdentity.php:40)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(90): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(13): CWebApplication->run()
REQUEST_URI=/blog/index.php?r=site/login
2018/01/18 07:30:50 [error] [php] Undefined variable: identity (C:\xampp\htdocs\blog\protected\models\LoginForm.php:54)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#1 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(90): LoginForm->validate()
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\blog\index.php(13): CWebApplication->run()
REQUEST_URI=/blog/index.php?r=site/login
2018/01/18 07:31:14 [error] [exception.CException] CException: Property "UserIdentity.erroCode" is not defined. in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\blog\protected\models\LoginForm.php(54): CComponent->__get('erroCode')
#1 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#2 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#4 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(90): CModel->validate()
#5 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/blog/index.php?r=site/login
HTTP_REFERER=http://localhost/blog/index.php?r=site/login
---
2018/01/24 02:58:42 [error] [exception.CException] CException: Property "Comment.authorLink" is not defined. in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('authorLink')
#1 C:\xampp\htdocs\blog\protected\components\views\recentComments.php(3): CActiveRecord->__get('authorLink')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, false)
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(RecentComments), 'C:\\xampp\\htdocs...', NULL, false)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CWidget.php(244): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, false)
#6 C:\xampp\htdocs\blog\protected\components\RecentComments.php(16): CWidget->render('recentComments')
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(182): CPortlet->run()
#9 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(15): CBaseController->widget('RecentComments', Array)
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(SiteController), 'C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(34): CController->render('index')
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#22 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/blog/
---
2018/01/24 02:58:49 [error] [exception.CException] CException: Property "Comment.authorLink" is not defined. in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('authorLink')
#1 C:\xampp\htdocs\blog\protected\components\views\recentComments.php(3): CActiveRecord->__get('authorLink')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, false)
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(RecentComments), 'C:\\xampp\\htdocs...', NULL, false)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CWidget.php(244): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, false)
#6 C:\xampp\htdocs\blog\protected\components\RecentComments.php(16): CWidget->render('recentComments')
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(182): CPortlet->run()
#9 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(15): CBaseController->widget('RecentComments', Array)
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(SiteController), 'C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(34): CController->render('index')
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#22 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/blog/
---
2018/01/24 03:26:53 [error] [php] Object of class Comment could not be converted to string (C:\xampp\htdocs\blog\protected\components\views\recentComments.php:3)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\widgets\CWidget.php(244): RecentComments->renderFile()
#2 C:\xampp\htdocs\blog\protected\components\RecentComments.php(16): RecentComments->render()
#3 C:\xampp\htdocs\yii\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(182): RecentComments->run()
#5 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(15): SiteController->widget()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): SiteController->renderInternal()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(787): SiteController->renderFile()
#10 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(34): SiteController->render()
#11 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#17 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\blog\index.php(13): CWebApplication->run()
REQUEST_URI=/blog/
2018/01/24 04:27:50 [error] [exception.CException] CException: Comment and its behaviors do not have a method or closure named "getUrl". in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(229): CComponent->__call('getUrl', Array)
#1 C:\xampp\htdocs\blog\protected\components\views\recentComments.php(4): CActiveRecord->__call('getUrl', Array)
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, false)
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(RecentComments), 'C:\\xampp\\htdocs...', NULL, false)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CWidget.php(244): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, false)
#6 C:\xampp\htdocs\blog\protected\components\RecentComments.php(16): CWidget->render('recentComments')
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(182): CPortlet->run()
#9 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(15): CBaseController->widget('RecentComments', Array)
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(SiteController), 'C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(34): CController->render('index')
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#22 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/blog/
---
2018/01/24 04:31:31 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\blog\protected\models\Comment.php:181)
Stack trace:
#0 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): RecentComments->renderInternal()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile()
#2 C:\xampp\htdocs\yii\framework\web\widgets\CWidget.php(244): RecentComments->renderFile()
#3 C:\xampp\htdocs\blog\protected\components\RecentComments.php(16): RecentComments->render()
#4 C:\xampp\htdocs\yii\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(182): RecentComments->run()
#6 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(15): SiteController->widget()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): SiteController->renderInternal()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(787): SiteController->renderFile()
#11 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(34): SiteController->render()
#12 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#15 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#18 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\blog\index.php(13): CWebApplication->run()
REQUEST_URI=/blog/
2018/01/24 04:35:40 [error] [exception.CException] CException: Property "Comment.title" is not defined. in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('title')
#1 C:\xampp\htdocs\blog\protected\models\Comment.php(174): CActiveRecord->__get('title')
#2 C:\xampp\htdocs\blog\protected\components\views\recentComments.php(4): Comment->getUrl()
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, false)
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(RecentComments), 'C:\\xampp\\htdocs...', NULL, false)
#6 C:\xampp\htdocs\yii\framework\web\widgets\CWidget.php(244): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, false)
#7 C:\xampp\htdocs\blog\protected\components\RecentComments.php(16): CWidget->render('recentComments')
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CPortlet.php(97): RecentComments->renderContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(182): CPortlet->run()
#10 C:\xampp\htdocs\blog\protected\views\layouts\column2.php(15): CBaseController->widget('RecentComments', Array)
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\blog\protected\extensions\yii-debug-toolbar\YiiDebugViewRenderer.php(40): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(93): YiiDebugViewRenderer->renderFile(Object(SiteController), 'C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(34): CController->render('index')
#16 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/blog/
---
2018/01/24 04:49:33 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "2". in C:\xampp\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('2')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('2')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/2')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/blog/index.php/post/2
---
2018/01/24 04:49:57 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "2". in C:\xampp\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('2')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('2')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/2')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/blog/index.php/post/2/
---
2018/01/24 04:50:14 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "1". in C:\xampp\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('1')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('1')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/1')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/blog/index.php/post/1/
---
2018/01/24 04:52:30 [error] [exception.CHttpException.404] CHttpException: The requested page does not exist. in C:\xampp\htdocs\blog\protected\controllers\PostController.php:242
Stack trace:
#0 C:\xampp\htdocs\blog\protected\controllers\PostController.php(59): PostController->loadModel()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): PostController->actionView()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/view')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/blog/index.php/post/view/
---
2018/01/24 06:39:38 [error] [system.db.CDbCommand] Error in preparing SQL: DELETE FROM YiiCache WHERE expire>0 AND expire<1516772378
2018/01/24 06:39:38 [error] [system.db.CDbCommand] CDbCommand::execute() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such table: YiiCache. The SQL statement executed was: DELETE FROM YiiCache WHERE expire>0 AND expire<1516772378.
2018/01/24 06:39:39 [error] [exception.CException] CException: PostController contains improperly nested widget tags in its view "C:\xampp\htdocs\blog\protected\views//layouts/column2.php". A CContentDecorator widget does not have an endWidget() call. in C:\xampp\htdocs\yii\framework\web\CBaseController.php:101
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#1 C:\xampp\htdocs\blog\protected\controllers\PostController.php(193): CController->render('index', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): PostController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/blog/index.php
HTTP_REFERER=http://localhost/blog/
---
